Resources:
  MyStackWithParams:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateBody: |
        Resources:
          MySecret:
            Type: AWS::SecretsManager::Secret
            Properties:
              Name: MySecretForNestedStack
              Description: "This secret has a dynamically generated secret password."
              GenerateSecretString:
                SecretStringTemplate: '{"username": "test-userr"}'
                GenerateStringKey: "password"
                PasswordLength: 10