AWSTemplateFormatVersion: '2010-09-09'

Resources:
  WaitConditionHandle:
    Type: AWS::CloudFormation::WaitConditionHandle
  AnotherNoOpStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      StackName: NestedStackOfNoOpStack
      TemplateURL: https://preprod-cf.s3.eu-central-1.amazonaws.com/main.yaml
