AWSTemplateFormatVersion: '2010-09-09'

Resources:
  NoopNestedStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateBody: |
        AWSTemplateFormatVersion: '2010-09-09'
        Resources:
          NoopResource:
            Type: AWS::CloudFormation::WaitCondition
