AWSTemplateFormatVersion: '2010-09-09'

Resources:
  AnotherNoOpStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateBody: >
        AWSTemplateFormatVersion: '2010-09-09'
        Resources:
          AnotherNoOp:
            Type: AWS::CloudFormation::WaitConditionHandle
