Resources:
  MyStackWithParams:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateBody: |
        Resources:
          NoopWaitConditionHandle:
            Type: AWS::CloudFormation::WaitConditionHandle

          NoopWaitCondition:
            Type: AWS::CloudFormation::WaitCondition
            DependsOn: NoopWaitConditionHandle
            Properties:
              Handle: !Ref NoopWaitConditionHandle
              Timeout: '1'