# main.yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: A simple EC2 instance
Mappings: 
  RegionMap:
    eu-west-2:
      AMI: ami-006589d4be3244642
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: {"Fn::FindInMap": ["RegionMap", {"Ref": "AWS::Region"}, "AMI"]}
      InstanceType: "t2.micro"
      Tags:
        - Key: "key"
          Value: "value5"
  SecondEC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://preprod-cf.s3.eu-central-1.amazonaws.com/01HMBS7FA91T21RKNA3BY7JYK6/11d53ebd6612a5b969993cf58c811e71.template
Outputs:
  InstanceRef:
    Value: !Ref MyEC2Instance