# substack.yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: A simple EC2 instance
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: eu-central-1a
      ImageId: ami-07df274a488ca9195
      InstanceType: t2.micro
      Tags:
        - Key: "key"
          Value: "value5"
