AWSTemplateFormatVersion: '2010-09-09'
Transform:
  - AWS::Serverless-2016-10-31

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'lambda-execution-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Path: /
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'poc-lambda'
      Role: !GetAtt LambdaExecutionRole.Arn
      PackageType: Zip
      Runtime: python3.9
      Handler: index.lambda_handler
      InlineCode: |
        def lambda_handler(event, context):
          print('Hello from Lambda!')
