AWSTemplateFormatVersion: '2010-09-09'
Description: A simple EC2 instance
Mappings: 
  RegionMap:
    eu-west-2:
      AMI: ami-006589d4be3244642
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: {"Fn::FindInMap": ["RegionMap", {"Ref": "AWS::Region"}, "AMI"]}
      InstanceType: t2.microo
      Tags:
      - Key: key
        Value: value5